#183230625 BC datation choices (1)
digITpro/catima pull request #10
Opened 2022-10-20 09:02 UTC by abstracts33d

#183230625 Traitement des dates négatives (BC)
#183230637 Réorganisation de l’option qui active/désactive l’utilisation des dates négatives (BC)

![image](https://user-images.githubusercontent.com/16547134/196904960-9e02bdd8-8312-4354-a218-b11375ddd2f4.png)
![image](https://user-images.githubusercontent.com/16547134/196905038-c1b006b2-6386-496c-b9c1-bf032ea4fb36.png)

2022-11-04 06:58 UTC, skyporter requested changes

2022-11-04 06:58 UTC, skyporter commented on app/models/choice.rb
> +    to_date_is_positive = JSON.parse(to_date).compact.select{|key, value| key != 'BC' }.map {|_key, value| value.to_i >= 0 }.all?
whitespace avant les "{", si `value` n'est pas utilisé alors faire `_value`

2022-11-04 06:58 UTC, skyporter commented on app/models/choice.rb
> +    to_date_is_positive = JSON.parse(to_date).compact.select{|key, value| key != 'BC' }.map {|_key, value| value.to_i >= 0 }.all?
a mon avis le `.all?` peut etre fait a la place du `.map`

2022-11-04 06:58 UTC, skyporter commented on app/models/choice.rb
> +    return unless choice_set&.datation?
white space après ou pas, mais soit consistent par rapport a l'autre validation

2022-11-04 06:58 UTC, skyporter commented on app/models/choice.rb
> +  validate :at_least_one_date_if_datation
**validate**_at_least...

2022-11-04 06:58 UTC, skyporter commented on app/models/field/complex_datation.rb
> +      end.all?
meme remarques que dans app/models/choice.rb

2022-11-04 06:58 UTC, skyporter commented on app/views/catalog_admin/items/_common_form_fields.html.erb
> +  <div class="base-errors pb-2"><%= @item.errors.where(:base).first&.full_message %></div>
pourquoi .first et pas to sentence ? `@item.errors.where(:base).full_message.to_sentence`

2022-11-09 14:22 UTC, abstracts33d commented on app/models/choice.rb
> +    to_date_is_positive = JSON.parse(to_date).compact.select{|key, value| key != 'BC' }.map {|_key, value| value.to_i >= 0 }.all?
yes

2022-11-09 14:23 UTC, abstracts33d commented on app/models/choice.rb
> +  validate :at_least_one_date_if_datation
yes

2022-11-09 14:24 UTC, abstracts33d commented on app/models/field/complex_datation.rb
> +      end.all?
yes

2022-11-09 14:34 UTC, closed without merging