Complex datation updates
digITpro/catima pull request #15
Opened 2022-11-02 10:00 UTC by abstracts33d

2022-11-17 15:13 UTC, skyporter requested changes

2022-11-17 15:13 UTC, skyporter commented on app/controllers/catalog_admin/choice_sets_controller.rb
> +      catalog: @choice_set.catalog.id, choice_set: @choice_set.id,
sur 2 lignes stp, et aussi évite de charger les données des relations pour juste récupérer un id:
```suggestion
      catalog: @choice_set.catalog_id, 
      choice_set: @choice_set.id,
```

2022-11-17 15:13 UTC, skyporter commented on app/controllers/catalog_admin/choice_sets_controller.rb
> +          name: choice.choice_set.choice_prefixed_label(choice, with_dates: @choice_set&.datation?)
pas besoin de "safe navigation" dans `@choice_set&.datation?` car `@choice_set` est forcément défini (selon la ligne 122)

2022-11-17 15:13 UTC, skyporter commented on app/controllers/catalog_admin/choices_controller.rb
> +            name: @choice.choice_set.choice_prefixed_label(@choice, with_dates: @choice_set&.datation?),
```suggestion
            name: @choice.choice_set.choice_prefixed_label(@choice, with_dates: @choice_set.datation?),
```

2022-11-17 15:13 UTC, skyporter commented on app/controllers/catalog_admin/choices_controller.rb
> +          }
attention, si ca devient trop complexe c'est mieux de render avec `jbuilder`

2022-11-17 15:13 UTC, skyporter commented on app/controllers/catalog_admin/choices_controller.rb
> +      if request.xhr? || params[:react]
je pense que c'est mieux de poster avec XHR et donc d'avoir une request de type "xhr?" plutot qu'un params:
`axios.defaults.headers.common["X-Requested-With"] = 'XMLHttpRequest';`

(on fait deja ca dans d'autres parties du code)
(et pareil ligne 48)

2022-11-17 15:13 UTC, skyporter commented on app/models/field/complex_datation.rb
> +    end
pour une meilleure lisibilité je recommande de ne pas faire avec un reject qui check un "not" mais le un select qui check un "true" => `reject{ !x || !y }` => `select{ x && y }`

2022-11-17 15:13 UTC, skyporter commented on app/models/search/complex_datation_strategy.rb
> +      end
`field_condition = "` peut etre sorti au niveau du "if"

2022-11-17 15:13 UTC, skyporter commented on app/models/search/complex_datation_strategy.rb
> +    return scope unless exclude_condition
a mon avis cette ligne ne sert a rien

2022-11-17 15:13 UTC, skyporter commented on app/presenters/choice_presenter.rb
> +    end
autant faire ca directement dans le if non ? je vois pas l'avantage d'avoir un if puis après un switch case sur les meme conditions que le if...

2022-11-17 15:13 UTC, skyporter commented on app/views/catalog_admin/items/_common_form_fields.html.erb
> +  <div class="base-errors pb-2"><%= @item.errors.where(:base).map{ |error| error.full_message}.to_sentence %></div>
mmhh, on a ce div meme si y a pas d'erreur.... pas top, aussi je penses qu'on peut accéder aux errors base ainsi `@item.errors(:base).full_messages.to_sentence` (a tester!)

2022-11-21 08:22 UTC, abstracts33d commented on app/controllers/catalog_admin/choice_sets_controller.rb
> +          name: choice.choice_set.choice_prefixed_label(choice, with_dates: @choice_set&.datation?)
yes

2022-11-21 08:30 UTC, abstracts33d commented on app/models/field/complex_datation.rb
> +    end
yes

2022-11-21 08:30 UTC, abstracts33d commented on app/models/search/complex_datation_strategy.rb
> +      end
yes

2022-11-21 08:31 UTC, abstracts33d commented on app/models/search/complex_datation_strategy.rb
> +    return scope unless exclude_condition
si aucune exlude condition n'est passée cela retourne le scope en quoi cela est il inutile ?

2022-11-21 08:34 UTC, abstracts33d commented on app/presenters/choice_presenter.rb
> +    end
yes

2022-11-21 09:33 UTC, skyporter commented on app/models/search/complex_datation_strategy.rb
> +    return scope unless exclude_condition
cela est inutile car le `else` du if du dessous fait deja ca

2022-11-21 11:51 UTC, abstracts33d commented on app/controllers/catalog_admin/choices_controller.rb
> +      if request.xhr? || params[:react]
yes

2022-11-21 11:52 UTC, abstracts33d commented on app/views/catalog_admin/items/_common_form_fields.html.erb
> +  <div class="base-errors pb-2"><%= @item.errors.where(:base).map{ |error| error.full_message}.to_sentence %></div>
yes

2022-11-29 08:24 UTC, skyporter commented on app/views/catalog_admin/items/_common_form_fields.html.erb
> +  <div class="base-errors pb-2"><%= @item.errors.full_messages.to_sentence %></div>
t'es sur de ca ? pourquoi on puts **toutes** les erreurs ainsi ?

2022-11-29 08:40 UTC, abstracts33d commented on app/models/search/complex_datation_strategy.rb
> +    return scope unless exclude_condition
yes

2022-11-29 08:49 UTC, abstracts33d commented on app/views/catalog_admin/items/_common_form_fields.html.erb
> +  <div class="base-errors pb-2"><%= @item.errors.full_messages.to_sentence %></div>
j'ai fais une loop sur where(:base)         (full_messages ne fonctionne pas avec where(:base)

2022-11-29 09:07 UTC, skyporter approved these changes

2023-03-06 10:55 UTC, closed without merging