#183568795 optimize choice set edit items
digITpro/catima pull request #16
Opened 2022-11-30 09:23 UTC by abstracts33d

![image](https://user-images.githubusercontent.com/16547134/204757342-59ec1279-b9a9-4657-ab13-eeb3d0ebeb4d.png)
![image](https://user-images.githubusercontent.com/16547134/204757504-2bf9f430-8381-4c89-9425-83d0760e4496.png)

2022-12-11 20:43 UTC, skyporter commented on config/initializers/cors.rb
> +end
pourquoi avoir ajouté cela ?

2022-12-11 20:43 UTC, skyporter commented on app/controllers/react/fields_controller.rb
> +               choices: filter_category_fields(choices.map{|choice| field.formated_choice(choice)}),
```suggestion
               choices: filter_category_fields(choices.map { |choice| field.formated_choice(choice) }),
```

2022-12-11 20:43 UTC, skyporter commented on app/models/field/choice_set.rb
> +      has_childrens: choice&.childrens&.any?,
```suggestion
      has_childrens: choice.childrens&.any?,
```

2022-12-11 20:43 UTC, skyporter commented on app/models/item_type.rb
> +    @all_fields ||= begin
a mon avis le begin/end n'est pas nécessaire

2022-12-11 20:43 UTC, skyporter commented on config/environments/test.rb
> +Rails.application.routes.default_url_options = { :host => "localhost:31337" }
t'es sur de ton coup la ? pourquoi ce changement ?

2022-12-11 20:43 UTC, skyporter commented on config/environments/development.rb
> +  :host => ENV.fetch('DOMAIN', "localhost:#{Rails::Server::Options.new.parse!(ARGV)[:Port]}"),
c'est quoi le soucis avec le fait d'utliser le port 3000 par default ?

2022-12-11 20:43 UTC, skyporter commented on config/initializers/cors.rb
> +end
je suis pas sur qu'on peu balancer ca sans explication/argumentation

2022-12-11 20:43 UTC, skyporter commented on db/migrate/20221130090048_update_editor_component_for_field_choice_set.rb
> +    Field::ChoiceSet.update_all(editor_component: 'ChoiceSetInput')
Pourquoi ce `update_all` sur les choice set ?

2022-12-11 20:43 UTC, skyporter commented on test/integration/api/v1/catalogs_test.rb
> +      "http://localhost:31337/#{catalog['slug']}",
ah nouveau je ne suis pas sur que ce soit une bonne idée de changer le port

2022-12-11 20:43 UTC, skyporter commented on test/integration/catalog_admin/choice_sets_test.rb
> +    sleep(2)
mériterai un commentaire dans le code, car un sleep posé comme ca c'est toujours inquiétant et ce serait bon de savoir pourquoi il est la

2022-12-11 20:43 UTC, skyporter commented on test/integration/catalog_admin/items_test.rb
> +      sleep(2)
meme commentaire que pour le sleep de choice_sets_test.rb

2022-12-11 20:43 UTC, skyporter commented
@abstracts33d il faudrait également merger master dans cette branch

2022-12-12 08:05 UTC, abstracts33d commented on config/environments/test.rb
> +Rails.application.routes.default_url_options = { :host => "localhost:31337" }
yes j' ai set le port dans la config capybara sinon il change a chaque fois

2022-12-12 08:06 UTC, abstracts33d commented on config/environments/development.rb
> +  :host => ENV.fetch('DOMAIN', "localhost:#{Rails::Server::Options.new.parse!(ARGV)[:Port]}"),
quand tu lance le serveur avec rails s -p xxxx les urls ne fonctionnent plus

2022-12-12 08:06 UTC, abstracts33d commented on db/migrate/20221130090048_update_editor_component_for_field_choice_set.rb
> +    Field::ChoiceSet.update_all(editor_component: 'ChoiceSetInput')
pour set leur editor_component  non présent avant et qui devient le composant react

2022-12-12 08:10 UTC, abstracts33d commented on test/integration/api/v1/catalogs_test.rb
> +      "http://localhost:31337/#{catalog['slug']}",
c' est le seul endroit dans les tests ou il est spécifié je peut le laisser sur 3000 et le fixer a 3000 dans capybara mais ca ne changera rien

2022-12-12 08:33 UTC, abstracts33d commented on test/integration/catalog_admin/choice_sets_test.rb
> +    sleep(2)
yes

2022-12-12 08:33 UTC, abstracts33d commented on test/integration/catalog_admin/items_test.rb
> +      sleep(2)
yes

2022-12-12 09:18 UTC, abstracts33d commented on config/environments/test.rb
> +Rails.application.routes.default_url_options = { :host => "localhost:31337" }
rolled back

2022-12-12 09:25 UTC, abstracts33d commented on config/environments/development.rb
> +  :host => ENV.fetch('DOMAIN', "localhost:#{Rails::Server::Options.new.parse!(ARGV)[:Port]}"),
rolled back

2022-12-12 09:25 UTC, abstracts33d commented on test/integration/api/v1/catalogs_test.rb
> +      "http://localhost:31337/#{catalog['slug']}",
rolled back

2022-12-12 09:27 UTC, abstracts33d commented on app/models/item_type.rb
> +    @all_fields ||= begin
yes

2022-12-12 09:27 UTC, abstracts33d commented on config/initializers/cors.rb
> +end
rolled back

2022-12-19 07:50 UTC, skyporter requested changes

2022-12-19 07:50 UTC, skyporter commented on Gemfile.lock
> +  rack-cors
on peut enlever ca non ?

2022-12-19 07:50 UTC, skyporter commented on config/environments/test.rb
> +Rails.application.routes.default_url_options = { :host => "localhost:3000" }
tu peux rollback ces changes qui stp?

2022-12-19 07:50 UTC, skyporter commented on app/models/field/choice_set.rb
> +      has_childrens: choice&.childrens&.any?,
ceci ne semble pas avoir été changé ?!

2022-12-19 13:36 UTC, abstracts33d commented on Gemfile.lock
> +  rack-cors
yes

2022-12-19 13:37 UTC, abstracts33d commented on config/environments/test.rb
> +Rails.application.routes.default_url_options = { :host => "localhost:3000" }
yes

2023-03-06 10:55 UTC, closed without merging